const MAX_SPACES_PER_USER = 6;
const MAX_UNITS_PER_SPACE = 12;
const MAX_UNITS_PER_UNIT = 0;
const MAX_UNITS_DEPTH = 0;

const LAUNCH_HEADER_BDRS = 16.8; // max for 48 height (16.8 * 1.25 + 3), see Corners
const LAUNCH_PAPER_BDRS = 32;
const LAUNCH_CARD_BDRS = 24;

const COMMON_USERS_DOCS_SPACE = 'launch-documents';

export {
  MAX_SPACES_PER_USER,
  MAX_UNITS_PER_SPACE,
  MAX_UNITS_PER_UNIT,
  MAX_UNITS_DEPTH,
  //
  LAUNCH_PAPER_BDRS,
  LAUNCH_HEADER_BDRS,
  LAUNCH_CARD_BDRS,
  COMMON_USERS_DOCS_SPACE,
};
