const MAX_SPACES_PER_USER = 6;
const MAX_UNITS_PER_SPACE = 12;
const MAX_UNITS_PER_UNIT = 0;
const MAX_UNITS_DEPTH = 0;

const COMMON_USERS_DOCS_SPACE = 'launch-documents';

export { MAX_SPACES_PER_USER, MAX_UNITS_PER_SPACE, MAX_UNITS_PER_UNIT, MAX_UNITS_DEPTH, COMMON_USERS_DOCS_SPACE };
